### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by bruno-rocha-movile** [snatchev/fastlane-branding-plugin#2]
Hey there, I'm trying to setup the branding plugin on my project, but after running fastlane, I get the following error instantly: 

/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require': /Library/Ruby/Gems/2.0.0/gems/branding-0.0.3/lib/branding/canvas.rb:16: syntax error, unexpected ',' (SyntaxError)
    def initialize(width:, height:)
                          ^
/Library/Ruby/Gems/2.0.0/gems/branding-0.0.3/lib/branding/canvas.rb:57: syntax error, unexpected keyword_end, expecting end-of-input
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in`require'
    from /Library/Ruby/Gems/2.0.0/gems/branding-0.0.3/lib/branding.rb:2:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in`require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-plugin-branding-0.1.2/lib/fastlane/plugin/branding/actions/branding_action.rb:1:in`<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:120:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:120:in`require'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-plugin-branding-0.1.2/lib/fastlane/plugin/branding.rb:15:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-plugin-branding-0.1.2/lib/fastlane/plugin/branding.rb:14:in`each'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-plugin-branding-0.1.2/lib/fastlane/plugin/branding.rb:14:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:133:in`require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:40:in`require'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/plugins/plugin_manager.rb:276:in `block in load_plugins'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/plugins/plugin_manager.rb:268:in`each'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/plugins/plugin_manager.rb:268:in `load_plugins'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/commands_generator.rb:17:in`start'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/bin/fastlane:5:in`<top (required)>'
    from /usr/local/bin/fastlane:22:in `load'
    from /usr/local/bin/fastlane:22:in`<main>'

Perhaps I need to update something that I'm not aware of? Other plugins work perfectly.

**Comment by snatchev** [comment]
Hello @bruno-rocha-movile, it looks like I used a Ruby 2.1+ syntax of named parameters described here:
http://stackoverflow.com/questions/13250447/can-i-have-required-named-parameters-in-ruby-2-x

There is no other good reason to use 2.1, so I will update the branding gem to not use that syntax.

Thank you for the report!

**Comment by snatchev** [comment]
@bruno-rocha-movile try updating to `fastlane-branding-plugin` to version `"~> 0.1.3"`

**Comment by bruno-rocha-movile** [comment]
@snatchev Works perfectly, thanks!
