### ISSUE TITLE
v0.1.4 ?

### ISSUE THREAD

**Issue by danhunsaker** [snatchev/fastlane-branding-plugin#4]
Android support exists on `master`, but there's no tag/release pointing to the changes, so it doesn't actually work in our projects without pointing at GitHub. What criteria need to be met to tag/release a new version? Anything I might be able to do to help with this effort?

**Comment by snatchev** [comment]
Thank you for the nudge. https://rubygems.org/gems/fastlane-plugin-branding/versions/0.1.4 is up.
